version: '2.1'

services:

  login-db:
    build: ./db
    environment:
      MYSQL_DATABASE: Ident
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      DATABASE_HOST: login-db
    ports:
      - 3308:3306

  login-ms:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_HOST: login-db
      MYSQL_PORT: 3308
      MYSQL_DATABASE: Ident
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "4000:4000"
    depends_on:
      - login-db
    restart: on-failure
